(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var l=this||self,aa=function(a){return a};var ba=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};var ca,n;a:{for(var da=["CLOSURE_FLAGS"],p=l,ea=0;ea<da.length;ea++)if(p=p[da[ea]],null==p){n=null;break a}n=p}var fa=n&&n[610401301];ca=null!=fa?fa:!1;var q;const ha=l.navigator;q=ha?ha.userAgentData||null:null;function ia(a){return ca?q?q.brands.some(({brand:b})=>b&&-1!=b.indexOf(a)):!1:!1}function r(a){var b;a:{if(b=l.navigator)if(b=b.userAgent)break a;b=""}return-1!=b.indexOf(a)};function t(){return ca?!!q&&0<q.brands.length:!1}function ja(){return t()?ia("Chromium"):(r("Chrome")||r("CriOS"))&&!(t()?0:r("Edge"))||r("Silk")};var ka=t()?!1:r("Trident")||r("MSIE");!r("Android")||ja();ja();r("Safari")&&(ja()||(t()?0:r("Coast"))||(t()?0:r("Opera"))||(t()?0:r("Edge"))||(t()?ia("Microsoft Edge"):r("Edg/"))||t()&&ia("Opera"));var la={},u=null;var ma="undefined"!==typeof Uint8Array,na=!ka&&"function"===typeof btoa;function v(a){return Array.prototype.slice.call(a)};const w="function"===typeof Symbol&&"symbol"===typeof Symbol()?Symbol():void 0;var x=w?(a,b)=>{a[w]|=b}:(a,b)=>{void 0!==a.g?a.g|=b:Object.defineProperties(a,{g:{value:b,configurable:!0,writable:!0,enumerable:!1}})};function oa(a){const b=A(a);1!==(b&1)&&(Object.isFrozen(a)&&(a=v(a)),B(a,b|1))}
var pa=w?(a,b)=>{a[w]&=~b}:(a,b)=>{void 0!==a.g&&(a.g&=~b)},A=w?a=>a[w]|0:a=>a.g|0,C=w?a=>a[w]:a=>a.g,B=w?(a,b)=>{a[w]=b}:(a,b)=>{void 0!==a.g?a.g=b:Object.defineProperties(a,{g:{value:b,configurable:!0,writable:!0,enumerable:!1}})};function qa(a){x(a,1);return a}function sa(a,b){B(b,(a|0)&-255)}function ta(a,b){B(b,(a|34)&-221)}function D(a){a=a>>11&1023;return 0===a?536870912:a};var E={};function F(a){return null!==a&&"object"===typeof a&&!Array.isArray(a)&&a.constructor===Object}let ua;var G;const va=[];B(va,39);G=Object.freeze(va);function wa(a){if(null==a)return a;if("string"===typeof a){if(!a)return;a=+a}if("number"===typeof a)return a}function xa(a,b,c){var d=!1;if(null!=a&&"object"===typeof a&&!(d=Array.isArray(a))&&a.i===E)return a;if(d){var e=d=A(a);0===e&&(e|=c&32);e|=c&2;e!==d&&B(a,e);return new b(a)}};let H;function ya(a,b){H=b;a=new a(b);H=void 0;return a};function za(a,b){return Aa(b)}
function Aa(a){switch(typeof a){case "number":return isFinite(a)?a:String(a);case "boolean":return a?1:0;case "object":if(a&&!Array.isArray(a)&&ma&&null!=a&&a instanceof Uint8Array){if(na){for(var b="",c=0,d=a.length-10240;c<d;)b+=String.fromCharCode.apply(null,a.subarray(c,c+=10240));b+=String.fromCharCode.apply(null,c?a.subarray(c):a);a=btoa(b)}else{void 0===b&&(b=0);if(!u){u={};c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split("");d=["+/=","+/","-_=","-_.","-_"];for(var e=
0;5>e;e++){var g=c.concat(d[e].split(""));la[e]=g;for(var h=0;h<g.length;h++){var f=g[h];void 0===u[f]&&(u[f]=h)}}}b=la[b];c=Array(Math.floor(a.length/3));d=b[64]||"";for(e=g=0;g<a.length-2;g+=3){var k=a[g],m=a[g+1];f=a[g+2];h=b[k>>2];k=b[(k&3)<<4|m>>4];m=b[(m&15)<<2|f>>6];f=b[f&63];c[e++]=""+h+k+m+f}h=0;f=d;switch(a.length-g){case 2:h=a[g+1],f=b[(h&15)<<2]||d;case 1:a=a[g],c[e]=""+b[a>>2]+b[(a&3)<<4|h>>4]+f+d}a=c.join("")}return a}}return a};function Ba(a,b,c){a=v(a);var d=a.length;const e=b&256?a[d-1]:void 0;d+=e?-1:0;for(b=b&512?1:0;b<d;b++)a[b]=c(a[b]);if(e){b=a[b]={};for(const g in e)b[g]=c(e[g])}return a}function Ca(a,b,c,d,e,g){if(null!=a){if(Array.isArray(a))a=e&&0==a.length&&A(a)&1?void 0:g&&A(a)&2?a:Da(a,b,c,void 0!==d,e,g);else if(F(a)){const h={};for(let f in a)h[f]=Ca(a[f],b,c,d,e,g);a=h}else a=b(a,d);return a}}
function Da(a,b,c,d,e,g){const h=d||c?A(a):0;d=d?!!(h&32):void 0;a=v(a);for(let f=0;f<a.length;f++)a[f]=Ca(a[f],b,c,d,e,g);c&&c(h,a);return a}function Ea(a){return a.i===E?a.toJSON():Aa(a)};function Fa(a,b,c=ta){if(null!=a){if(ma&&a instanceof Uint8Array)return b?a:new Uint8Array(a);if(Array.isArray(a)){const d=A(a);return d&2?a:!b||d&68||!(d&32||0===d)?Da(a,Fa,d&4?ta:c,!0,!1,!0):(B(a,d|34),a)}a.i===E&&(b=a.h,c=C(b),a=c&2?a:ya(a.constructor,Ga(b,c,!0)));return a}}function Ga(a,b,c){const d=c||b&2?ta:sa,e=!!(b&32);a=Ba(a,b,g=>Fa(g,e,d));x(a,32|(c?2:0));return a}function Ha(a){const b=a.h,c=C(b);return c&2?ya(a.constructor,Ga(b,c,!1)):a};var Ia=function(a,b){a=a.h;return K(a,C(a),b)},K=function(a,b,c,d){if(-1===c)return null;if(c>=D(b)){if(b&256)return a[a.length-1][c]}else{var e=a.length;if(d&&b&256&&(d=a[e-1][c],null!=d))return d;b=c+(+!!(b&512)-1);if(b<e)return a[b]}};function M(a,b,c,d,e){var g=D(b);if(c>=g||e){e=b;if(b&256)g=a[a.length-1];else{if(null==d)return;g=a[g+(+!!(b&512)-1)]={};e|=256}g[c]=d;e!==b&&B(a,e)}else a[c+(+!!(b&512)-1)]=d,b&256&&(a=a[a.length-1],c in a&&delete a[c])}
var Q=function(a,b,c){return void 0!==N(a,b,O(a,P,c))},Ja=function(a,b){a=Ia(a,b);return null==a?a:"boolean"===typeof a||"number"===typeof a?!!a:void 0};function Ka(a,b,c,d){const e=a.h,g=C(e);if(g&2)throw Error();M(e,g,b,c!==d?c:void 0);return a}var O=function(a,b,c){a=a.h;return La(a,C(a),b)===c?c:-1};function La(a,b,c){let d=0;for(let e=0;e<c.length;e++){const g=c[e];null!=K(a,b,g)&&(0!==d&&M(a,b,d),d=g)}return d}
var N=function(a,b,c,d){a=a.h;const e=C(a),g=K(a,e,c,d);b=xa(g,b,e);b!==g&&null!=b&&M(a,e,c,b,d);return b},R=function(a,b,c){b=N(a,b,c,!1);if(null==b)return b;a=a.h;const d=C(a);if(!(d&2)){const e=Ha(b);e!==b&&(b=e,M(a,d,c,b,!1))}return b},Na=function(a,b){var c=a.h,d=C(c);a=!!(d&2);var e=a?1:2,g=!!(d&2),h=d&2,f=K(c,d,b);Array.isArray(f)||(f=G);var k=A(f);k&1||qa(f);h?k&2||x(f,34):k&32&&!(k&2)&&pa(f,32);h=f;if(h!==G&&A(h)&4)3!==e&&(g?2===e&&(e=A(h),h=v(h),B(h,e),M(c,d,b,h)):(g=Object.isFrozen(h),
1===e?g||Object.freeze(h):(e=A(h),f=e&-35,g&&(h=v(h),e=0,M(c,d,b,h)),e!==f&&B(h,f)))),b=h;else{k=h;var m=Ma;h=!!(d&2);f=!!(A(k)&2);g=k;!h&&f&&(k=v(k));var y=d|(f?2:0);f=f||void 0;let I=0,L=0;for(;I<k.length;I++){const z=xa(k[I],m,y);void 0!==z&&(f=f||C(z.h)&2,k[L++]=z)}L<I&&(k.length=L);m=A(k);y=m|5;f=f?y&-9:y|8;m!=f&&(Object.isFrozen(k)&&(k=v(k)),B(k,f));g!==k&&M(c,d,b,k);(h&&2!==e||1===e)&&Object.freeze(k);b=k}if(!(a||A(b)&8)){for(a=0;a<b.length;a++)c=b[a],d=Ha(c),c!==d&&(b[a]=d);x(b,8)}return b},
S=function(a,b){a=Ja(a,b);return null!=a?a:!1},T=function(a,b){a=wa(Ia(a,b));return null!=a?a:0},U=function(a,b){a=Ia(a,b);a=null==a||"string"===typeof a?a:void 0;return null!=a?a:""};var V=class{constructor(a){a:{null==a&&(a=H);H=void 0;if(null==a){var b=96;a=[]}else{if(!Array.isArray(a))throw Error();b=A(a);if(b&64)break a;var c=a;b|=64;var d=c.length;if(d){var e=d-1;d=c[e];if(F(d)){b|=256;const g=+!!(b&512)-1;e-=g;if(1024<=e){e=1023+g;const h=c.length;for(let f=e;f<h;f++){const k=c[f];null!=k&&k!==d&&(d[f-g]=k)}c.length=e+1;c[e]=d;e=1023}b=b&-2095105|(e&1023)<<11}}}B(a,b)}this.h=a}toJSON(){if(ua)var a=Oa(this,this.h,!1);else a=Da(this.h,Ea,void 0,void 0,!1,!1),a=Oa(this,a,!0);
return a}};V.prototype.i=E;V.prototype.toString=function(){return Oa(this,this.h,!1).toString()};
function Oa(a,b,c){var d=a.constructor.j,e=D(C(c?a.h:b)),g=!1;if(d){if(!c){b=v(b);var h;if(b.length&&F(h=b[b.length-1]))for(g=0;g<d.length;g++)if(d[g]>=e){Object.assign(b[b.length-1]={},h);break}g=!0}e=b;c=!c;h=C(a.h);a=D(h);h=+!!(h&512)-1;var f;for(let J=0;J<d.length;J++){var k=d[J];if(k<a){k+=h;var m=e[k];null==m?e[k]=c?G:qa([]):c&&m!==G&&oa(m)}else{if(!f){var y=void 0;e.length&&F(y=e[e.length-1])?f=y:e.push(f={})}m=f[k];null==f[k]?f[k]=c?G:qa([]):c&&m!==G&&oa(m)}}}d=b.length;if(!d)return b;let I,
L;if(F(f=b[d-1])){a:{var z=f;y={};e=!1;for(let J in z)c=z[J],Array.isArray(c)&&c!=c&&(e=!0),null!=c?y[J]=c:e=!0;if(e){for(let J in y){z=y;break a}z=null}}z!=f&&(I=!0);d--}for(;0<d;d--){f=b[d-1];if(null!=f)break;L=!0}if(!I&&!L)return b;var ra;g?ra=b:ra=Array.prototype.slice.call(b,0,d);b=ra;g&&(b.length=d);z&&b.push(z);return b};var Ma=class extends V{},W=[2,3,4];var Pa=class extends V{};var Qa=class extends V{};var Ra=class extends V{};Ra.j=[6];var Sa=class extends V{constructor(){super()}};var Ta=class extends V{constructor(){super()}},Ua=[2];var Va=class extends V{};Va.j=[2];var Wa=class extends V{};var Xa=class extends V{};var Ya=class extends V{};var Za=function(a){return b=>{if(null==b||""==b)b=new a;else{b=JSON.parse(b);if(!Array.isArray(b))throw Error(void 0);x(b,32);b=ya(a,b)}return b}}(class extends V{}),P=[2,3,4,5,6,7];var $a;var ab=class{constructor(a){this.g=a}toString(){return this.g+""}},bb={},cb=function(a){if(void 0===$a){var b=null;var c=l.trustedTypes;if(c&&c.createPolicy){try{b=c.createPolicy("goog#html",{createHTML:aa,createScript:aa,createScriptURL:aa})}catch(d){l.console&&l.console.error(d.message)}$a=b}else $a=b}a=(b=$a)?b.createScriptURL(a):a;return new ab(a,bb)};var db=function(){this.g=document||{cookie:""}};
db.prototype.set=function(a,b,c){let d,e,g,h=!1,f;"object"===typeof c&&(f=c.u,h=c.v||!1,g=c.domain||void 0,e=c.path||void 0,d=c.s);if(/[;=\s]/.test(a))throw Error('Invalid cookie name "'+a+'"');if(/[;\r\n]/.test(b))throw Error('Invalid cookie value "'+b+'"');void 0===d&&(d=-1);this.g.cookie=a+"="+b+(g?";domain="+g:"")+(e?";path="+e:"")+(0>d?"":0==d?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date(Date.now()+1E3*d)).toUTCString())+(h?";secure":"")+(null!=f?";samesite="+f:"")};
db.prototype.get=function(a,b){const c=a+"=",d=(this.g.cookie||"").split(";");for(let e=0,g;e<d.length;e++){g=ba(d[e]);if(0==g.lastIndexOf(c,0))return g.slice(c.length);if(g==a)return""}return b};/*

 SPDX-License-Identifier: Apache-2.0
*/
function eb(a,...b){if(0===b.length)return cb(a[0]);let c=a[0];for(let d=0;d<b.length;d++)c+=encodeURIComponent(b[d])+a[d+1];return cb(c)};class fb{constructor(){this.l=new db;this.g="";this.m=a=>{a:{let k;try{k=Za(a.data)}catch(m){break a}if(Q(k,Ra,4)){var b=R(k,Ra,O(k,P,4)),c=Na(b,6),d;c.length&&(d=gb(c));c={event:U(b,1)||void 0,category:U(b,2)||void 0,action:U(b,3)||void 0,label:U(b,4)||void 0,value:T(b,5)||void 0,nonInteraction:S(b,13)?"True":"False",additionalParams:d||void 0};if(void 0!==N(b,Qa,12,!1)){var e=R(b,Qa,12);c.recommendations={targetPage:U(e,1),targetType:T(e,2),targetRank:T(e,3),targetIdenticalDescriptions:T(e,4),targetTitleWords:T(e,
5),targetDescriptionWords:T(e,6),experiment:U(e,7)};d="";for(var g of window.dataLayer)if("experiment"in g&&"baseIds"in g.experiment){d=g.experiment.baseIds;break}(d=hb(d,U(e,7)))&&S(e,8)&&(c.experiment={ids:d})}else c.recommendations={targetPage:void 0,targetType:void 0,targetRank:void 0,targetIdenticalDescriptions:void 0,targetTitleWords:void 0,targetDescriptionWords:void 0};if(!("experiment"in c))for(var h of window.dataLayer)if("experiment"in h&&"ids"in h.experiment&&h.experiment.ids){c.experiment=
{ids:h.experiment.ids};break}g=R(b,Pa,11);if(void 0!==N(b,Pa,11,!1)&&null!==g){g=ib(g);for(var f of Object.keys(g))c[f]=g[f]}window.dataLayer.push(c)}else if(Q(k,Va,3)){f=R(k,Va,O(k,P,3));g=Na(f,2);let m;g.length&&(m=gb(g));g={event:"trackPageview",pageName:U(f,1),additionalParams:m||void 0,nonInteraction:S(f,3)||void 0,ratingsCount:T(f,4)||void 0,ratingsValue:T(f,5)||void 0};h=R(f,Pa,6);if(void 0!==N(f,Pa,6,!1)&&null!==h){f=ib(h);for(b of Object.keys(f))g[b]=f[b]}window.dataLayer.push(g)}else Q(k,
Wa,7)?(f=R(k,Wa,O(k,P,7)),window.dataLayer.push({parentContext:{referrer:U(f,2)||"",_ga_devsiteCookie:U(f,1)||""}})):Q(k,Xa,6)?(f=R(k,Xa,O(k,P,6)),g=this.g,h=R(f,Qa,9)||new Qa,b=U(f,10)||void 0,f={experiment:{ids:(S(h,8)?hb(b,U(h,7)):b)||void 0,baseIds:b||void 0},hostContext:{internalUser:U(f,1)||void 0,pageType:U(f,8)||void 0,projectName:U(f,6)||void 0,signedIn:U(f,2)||void 0,tenant:U(f,5)||void 0,thirdPartyCookieAccepted:g.length?"True":"False"},language:{machineTranslated:U(f,7)||void 0,requested:U(f,
3)||void 0,served:U(f,4)||void 0},recommendations:{sourcePage:U(h,1),sourceType:T(h,2),sourceRank:T(h,3),sourceIdenticalDescriptions:T(h,4),sourceTitleWords:T(h,5),sourceDescriptionWords:T(h,6),experiment:U(h,7)}},window.dataLayer.push(f)):Q(k,Ya,5)?(f=R(k,Ya,O(k,P,5)),window.dataLayer.push({originalUrlParameters:{dclid:U(f,1)||void 0,gclid:U(f,2)||void 0,utmCampaign:U(f,3)||void 0,utmContent:U(f,4)||void 0,utmCreativeFormat:U(f,8)||void 0,utmMarketingTactic:U(f,10)||void 0,utmMedium:U(f,5)||void 0,
utmSource:U(f,6)||void 0,utmSourcePlatform:U(f,9)||void 0,utmTerm:U(f,7)||void 0}})):null!=Ja(k,O(k,P,2))&&(window.dataLayer=window.dataLayer||[],window.dataLayer.push({"gtm.start":(new Date).getTime(),event:"gtm.js"}),f=document.getElementsByTagName("script")[0],g=document.createElement("script"),g.async=!0,h=eb`//www.googletagmanager.com/gtm.js?id=GTM-PBZPJDG`,g.src=h instanceof ab&&h.constructor===ab?h.g:"type_error:TrustedResourceUrl",(h=(h=null==(e=(c=(g.ownerDocument&&g.ownerDocument.defaultView||
window).document).querySelector)?void 0:e.call(c,"script[nonce]"))?h.nonce||h.getAttribute("nonce")||"":"")&&g.setAttribute("nonce",h),f.parentNode.insertBefore(g,f))}};window.addEventListener("message",this.m)}o(a){this.g=this.l.get("_ga_devsite")||"";var b=new Sa;if(null!=a){if("boolean"!==typeof a){var c=typeof a;throw Error(`Expected boolean but got ${"object"!=c?c:a?Array.isArray(a)?"array":c:"null"}: ${a}`);}a=!!a}a=Ka(b,1,a,!1);b=this.g;if(null!=b&&"string"!==typeof b)throw Error();b=Ka(a,
2,b,"");a=new Ta;null==b&&(b=void 0);var d=a.h;const e=C(d);if(e&2)throw Error();let g=La(d,e,Ua);g&&2!==g&&null!=b&&M(d,e,g);M(d,e,2,b);if(window.parent!==window){b=window.parent;d=b.postMessage;a:{ua=!0;try{c=JSON.stringify(a.toJSON(),za);break a}finally{ua=!1}c=void 0}d.call(b,c,"*")}}}fb.prototype.notifyIframeReady=fb.prototype.o;
function gb(a){const b={};for(const c of a){a=U(c,1);let d;U(c,O(c,W,2))?d=U(c,O(c,W,2)):T(c,O(c,W,3))?d=T(c,O(c,W,3)):null!=Ja(c,O(c,W,4))&&(d=S(c,O(c,W,4))?"True":"False");b[a]=d}return b}
function ib(a){const b={};if(!a)return b;b.hasProfile=S(a,6)?"True":"False";b.practitionerType=U(a,1)||"Property not set";b.profileCreationMethod=U(a,4)||"Property not set";b.profileHasInterests=S(a,12)?"True":"False";b.profileInterests=U(a,13)||"Property not set";b.profileHasJobTitle=S(a,10)?"True":"False";b.profileHasLocation=S(a,7)?"True":"False";b.profileHasPronoun=S(a,9)?"True":"False";b.profileIsPublic=S(a,8)?"True":"False";b.profileSocialLinks=U(a,11)||"Property not set";b.profileBadgeEmailOptIn=
S(a,5)?"True":"False";b.profileFeedbackEmailOptIn=S(a,2)?"True":"False";b.profileNewsletterEmailOptIn=S(a,3)?"True":"False";return b}function hb(a,b){if(a||b){if(a&&!b)return a;if(b&&!a)return b;b=new Set(b.split(","));a=[...(new Set([...(new Set(a.split(","))),...b]))];a.sort();return a.join(",")}}var jb=fb,X=["AnalyticsLibrary"],Y=l;X[0]in Y||"undefined"==typeof Y.execScript||Y.execScript("var "+X[0]);
for(var Z;X.length&&(Z=X.shift());)X.length||void 0===jb?Y[Z]&&Y[Z]!==Object.prototype[Z]?Y=Y[Z]:Y=Y[Z]={}:Y[Z]=jb;}).call(this);
