(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var aa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a},ba=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},ca=ba(this),da=function(a,b){if(b)a:{var c=ca;a=a.split(".");for(var e=0;e<
a.length-1;e++){var f=a[e];if(!(f in c))break a;c=c[f]}a=a[a.length-1];e=c[a];b=b(e);b!=e&&null!=b&&aa(c,a,{configurable:!0,writable:!0,value:b})}};
da("String.prototype.replaceAll",function(a){return a?a:function(b,c){if(b instanceof RegExp&&!b.global)throw new TypeError("String.prototype.replaceAll called with a non-global RegExp argument.");return b instanceof RegExp?this.replace(b,c):this.replace(new RegExp(String(b).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"),"g"),c)}});
var d=this||self,m=function(a,b){a=a.split(".");var c=d;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var e;a.length&&(e=a.shift());)a.length||void 0===b?c[e]&&c[e]!==Object.prototype[e]?c=c[e]:c=c[e]={}:c[e]=b},p=function(a){return a};var q=new Map([]);q.set("devsite-a11y-announce",{src:"/developers/js/devsite_devsite_a11y_announce_module.js"});q.set("devsite-analytics",{src:"/developers/js/devsite_devsite_analytics_module.js"});q.set("devsite-analytics-scope",{src:"/developers/js/devsite_devsite_analytics_scope_module.js"});q.set("devsite-anselm",{src:"/developers/js/devsite_devsite_anselm_module.js"});q.set("devsite-api-getstarted",{src:"/developers/js/devsite_devsite_api_getstarted_module.js"});q.set("devsite-apix",{src:"/developers/js/devsite_devsite_apix_module.js"});
q.set("devsite-apix-index",{src:"/developers/js/devsite_devsite_apix_index_module.js"});q.set("devsite-apix-snippets",{src:"/developers/js/devsite_devsite_apix_snippets_module.js"});q.set("devsite-appearance-selector",{src:"/developers/js/devsite_devsite_appearance_selector_module.js"});q.set("devsite-author-page-insights",{src:"/developers/js/devsite_devsite_author_page_insights_module.js"});q.set("devsite-badge-awarded",{src:"/developers/js/devsite_devsite_badge_awarded_module.js"});
q.set("devsite-badge-awarder",{src:"/developers/js/devsite_devsite_badge_awarder_module.js"});q.set("devsite-badge-redeemer",{src:"/developers/js/devsite_devsite_badge_redeemer_module.js"});q.set("devsite-badger",{src:"/developers/js/devsite_devsite_badger_module.js"});q.set("devsite-book-nav",{src:"/developers/js/devsite_devsite_book_nav_module.js"});q.set("devsite-bookmark",{src:"/developers/js/devsite_devsite_bookmark_module.js"});q.set("devsite-carousel",{src:"/developers/js/devsite_devsite_carousel_module.js"});
q.set("devsite-catalog",{src:"/developers/js/devsite_devsite_catalog_module.js"});q.set("devsite-catalog-body-badges",{src:"/developers/js/devsite_devsite_catalog_body_badges_module.js"});q.set("devsite-chart",{src:"/developers/js/devsite_devsite_chart_module.js"});q.set("devsite-checkbox",{src:"/developers/js/devsite_devsite_checkbox_module.js"});q.set("devsite-code",{src:"/developers/js/devsite_devsite_code_module.js"});q.set("devsite-codelab-catalog",{src:"/developers/js/devsite_devsite_codelab_catalog_module.js"});
q.set("devsite-concierge",{src:"/developers/js/devsite_devsite_concierge_module.js"});q.set("devsite-concierge-ai-panel",{src:"/developers/js/devsite_devsite_concierge_ai_panel_module.js"});q.set("devsite-concierge-api-explorer-panel",{src:"/developers/js/devsite_devsite_concierge_api_explorer_panel_module.js"});q.set("devsite-concierge-apix",{src:"/developers/js/devsite_devsite_concierge_apix_module.js"});q.set("devsite-concierge-info-panel",{src:"/developers/js/devsite_devsite_concierge_info_panel_module.js"});
q.set("devsite-concierge-my-activity-panel",{src:"/developers/js/devsite_devsite_concierge_my_activity_panel_module.js"});q.set("devsite-concierge-recommendations-panel",{src:"/developers/js/devsite_devsite_concierge_recommendations_panel_module.js"});q.set("devsite-content",{src:"/developers/js/devsite_devsite_content_module.js"});q.set("devsite-content-excellence",{src:"/developers/js/devsite_devsite_content_excellence_module.js"});q.set("devsite-cookie-consent",{src:"/developers/js/devsite_devsite_cookie_consent_module.js"});
q.set("devsite-countdown",{src:"/developers/js/devsite_devsite_countdown_module.js"});q.set("devsite-credentials-dialog",{src:"/developers/js/devsite_devsite_credentials_dialog_module.js"});q.set("devsite-cse",{src:"/developers/js/devsite_devsite_cse_module.js"});q.set("devsite-device",{src:"/developers/js/devsite_devsite_device_module.js"});q.set("devsite-devprofile",{src:"/developers/js/devsite_devsite_devprofile_module.js"});q.set("devsite-dialog",{src:"/developers/js/devsite_devsite_dialog_module.js"});
q.set("devsite-dropdown-list",{src:"/developers/js/devsite_devsite_dropdown_list_module.js"});q.set("devsite-dynamic-content",{src:"/developers/js/devsite_devsite_dynamic_content_module.js"});q.set("devsite-dynamic-hero",{src:"/developers/js/devsite_devsite_dynamic_hero_module.js"});q.set("devsite-edit-profile",{src:"/developers/js/devsite_devsite_edit_profile_module.js"});q.set("devsite-expandable",{src:"/developers/js/devsite_devsite_expandable_module.js"});q.set("devsite-extradory",{src:"/developers/js/devsite_devsite_extradory_module.js"});
q.set("devsite-fast-track-profile-creator",{src:"/developers/js/devsite_devsite_fast_track_profile_creator_module.js"});q.set("devsite-feature-tooltip",{src:"/developers/js/devsite_devsite_feature_tooltip_module.js"});q.set("devsite-feedback",{src:"/developers/js/devsite_devsite_feedback_module.js"});q.set("devsite-filter",{src:"/developers/js/devsite_devsite_filter_module.js"});q.set("devsite-footer-linkboxes",{src:"/developers/js/devsite_devsite_footer_linkboxes_module.js"});
q.set("devsite-footer-promos",{src:"/developers/js/devsite_devsite_footer_promos_module.js"});q.set("devsite-footer-utility",{src:"/developers/js/devsite_devsite_footer_utility_module.js"});q.set("devsite-fully-clickable",{src:"/developers/js/devsite_devsite_fully_clickable_module.js"});q.set("devsite-googler-buttons",{src:"/developers/js/devsite_devsite_googler_buttons_module.js"});q.set("devsite-hats-survey",{src:"/developers/js/devsite_devsite_hats_survey_module.js"});q.set("devsite-header",{src:"/developers/js/devsite_devsite_header_module.js"});
q.set("devsite-heading-link",{src:"/developers/js/devsite_devsite_heading_link_module.js"});q.set("devsite-iframe",{src:"/developers/js/devsite_devsite_iframe_module.js"});q.set("devsite-info-popout",{src:"/developers/js/devsite_devsite_info_popout_module.js"});q.set("devsite-jsfiddle-button",{src:"/developers/js/devsite_devsite_jsfiddle_button_module.js"});q.set("devsite-json-validator",{src:"/developers/js/devsite_devsite_json_validator_module.js"});q.set("devsite-jump-to",{src:"/developers/js/devsite_devsite_jump_to_module.js"});
q.set("devsite-language-selector",{src:"/developers/js/devsite_devsite_language_selector_module.js"});q.set("devsite-lightbox",{src:"/developers/js/devsite_devsite_lightbox_module.js"});q.set("devsite-mathjax",{src:"/developers/js/devsite_devsite_mathjax_module.js"});q.set("devsite-mdc",{src:"/developers/js/devsite_devsite_mdc_module.js"});q.set("devsite-multiple-choice",{src:"/developers/js/devsite_devsite_multiple_choice_module.js"});q.set("devsite-mwc",{src:"/developers/js/devsite_devsite_mwc_module.js"});
q.set("devsite-my-activity-light",{src:"/developers/js/devsite_devsite_my_activity_light_module.js"});q.set("devsite-my-community",{src:"/developers/js/devsite_devsite_my_community_module.js"});q.set("devsite-nav-buttons",{src:"/developers/js/devsite_devsite_nav_buttons_module.js"});q.set("devsite-notification",{src:"/developers/js/devsite_devsite_notification_module.js"});q.set("devsite-pagination",{src:"/developers/js/devsite_devsite_pagination_module.js"});q.set("devsite-panel",{src:"/developers/js/devsite_devsite_panel_module.js"});
q.set("devsite-playlist",{src:"/developers/js/devsite_devsite_playlist_module.js"});q.set("devsite-playlist-earnable-badges",{src:"/developers/js/devsite_devsite_playlist_earnable_badges_module.js"});q.set("devsite-playlist-summary",{src:"/developers/js/devsite_devsite_playlist_summary_module.js"});q.set("devsite-product-catalog",{src:"/developers/js/devsite_devsite_product_catalog_module.js"});q.set("devsite-profile-card",{src:"/developers/js/devsite_devsite_profile_card_module.js"});
q.set("devsite-progress",{src:"/developers/js/devsite_devsite_progress_module.js"});q.set("devsite-quiz",{src:"/developers/js/devsite_devsite_quiz_module.js"});q.set("devsite-recommendations",{src:"/developers/js/devsite_devsite_recommendations_module.js"});q.set("devsite-recommendations-dropdown",{src:"/developers/js/devsite_devsite_recommendations_dropdown_module.js"});q.set("devsite-recommendations-sidebar",{src:"/developers/js/devsite_devsite_recommendations_sidebar_module.js"});
q.set("devsite-recommended-content",{src:"/developers/js/devsite_devsite_recommended_content_module.js"});q.set("devsite-reference-results",{src:"/developers/js/devsite_devsite_reference_results_module.js"});q.set("devsite-related-entities",{src:"/developers/js/devsite_devsite_related_entities_module.js"});q.set("devsite-rich-tooltip",{src:"/developers/js/devsite_devsite_rich_tooltip_module.js"});q.set("devsite-search",{src:"/developers/js/devsite_devsite_search_module.js"});
q.set("devsite-select",{src:"/developers/js/devsite_devsite_select_module.js"});q.set("devsite-selector",{src:"/developers/js/devsite_devsite_selector_module.js"});q.set("devsite-shell",{src:"/developers/js/devsite_devsite_shell_module.js"});q.set("devsite-shell-activate-button",{src:"/developers/js/devsite_devsite_shell_activate_button_module.js"});q.set("devsite-sitemask",{src:"/developers/js/devsite_devsite_sitemask_module.js"});q.set("devsite-snackbar",{src:"/developers/js/devsite_devsite_snackbar_module.js"});
q.set("devsite-sort",{src:"/developers/js/devsite_devsite_sort_module.js"});q.set("devsite-spinner",{src:"/developers/js/devsite_devsite_spinner_module.js"});q.set("devsite-support-form",{src:"/developers/js/devsite_devsite_support_form_module.js"});q.set("devsite-tabs",{src:"/developers/js/devsite_devsite_tabs_module.js"});q.set("devsite-thumb-rating",{src:"/developers/js/devsite_devsite_thumb_rating_module.js"});q.set("devsite-toc",{src:"/developers/js/devsite_devsite_toc_module.js"});
q.set("devsite-tooltip",{src:"/developers/js/devsite_devsite_tooltip_module.js"});q.set("devsite-topic",{src:"/developers/js/devsite_devsite_topic_module.js"});q.set("devsite-tracking-question",{src:"/developers/js/devsite_devsite_tracking_question_module.js"});q.set("devsite-user",{src:"/developers/js/devsite_devsite_user_module.js"});q.set("devsite-var",{src:"/developers/js/devsite_devsite_var_module.js"});q.set("devsite-version-selector",{src:"/developers/js/devsite_devsite_version_selector_module.js"});
q.set("devsite-video",{src:"/developers/js/devsite_devsite_video_module.js"});q.set("devsite-view-release-notes",{src:"/developers/js/devsite_devsite_view_release_notes_module.js"});q.set("devsite-view-release-notes-dialog",{src:"/developers/js/devsite_devsite_view_release_notes_dialog_module.js"});q.set("devsite-visibility-analytics",{src:"/developers/js/devsite_devsite_visibility_analytics_module.js"});q.set("devsite-vplus",{src:"/developers/js/devsite_devsite_vplus_module.js"});
q.set("devsite-wall-acknowledgement",{src:"/developers/js/devsite_devsite_wall_acknowledgement_module.js"});q.set("devsite-youtube",{src:"/developers/js/devsite_devsite_youtube_module.js"});q.set("google-codelab",{src:"/developers/js/devsite_google_codelab_module.js"});q.set("google-codelab-about",{src:"/developers/js/devsite_google_codelab_about_module.js"});q.set("google-codelab-analytics",{src:"/developers/js/devsite_google_codelab_analytics_module.js"});q.set("google-codelab-step",{src:"/developers/js/devsite_google_codelab_step_module.js"});
q.set("google-codelab-survey",{src:"/developers/js/devsite_google_codelab_survey_module.js"});q.set("devsite-avatar",{src:"/developers/js/devsite_devsite_avatar_module.js"});q.set("devsite-activity-list",{src:"/developers/js/devsite_devsite_activity_list_module.js"});q.set("devsite-badge",{src:"/developers/js/devsite_devsite_badge_module.js"});q.set("devsite-card",{src:"/developers/js/devsite_devsite_card_module.js"});q.set("devsite-collection",{src:"/developers/js/devsite_devsite_collection_module.js"});
q.set("devsite-collection-list",{src:"/developers/js/devsite_devsite_collection_list_module.js"});q.set("devsite-profile",{src:"/developers/js/devsite_devsite_profile_module.js"});q.set("devsite-profile-dashboard",{src:"/developers/js/devsite_devsite_profile_dashboard_module.js"});q.set("devsite-profile-interests",{src:"/developers/js/devsite_devsite_profile_interests_module.js"});q.set("devsite-profile-recommendations",{src:"/developers/js/devsite_devsite_profile_recommendations_module.js"});
q.set("devsite-profile-wizard",{src:"/developers/js/devsite_devsite_profile_wizard_module.js"});q.set("devsite-profile-router",{src:"/developers/js/devsite_devsite_profile_router_module.js"});q.set("devsite-profiles-splash",{src:"/developers/js/devsite_devsite_profiles_splash_module.js"});m("DevsiteAppAuthorizedElements",q);m("DevsiteAppTenantCustomized",!0);var ea={wc:0,vc:1,Yb:6,Wb:8,ec:12,fc:14,hc:17,lc:18,nc:21,pc:25,pa:37,qc:38,Ca:40,lb:45,X:47,C:50,O:52,K:62,Sa:63,Qb:66,Gb:70,F:73,tb:74,Z:75,Nb:76,Oa:77,Qa:80,L:81,fb:82,Ka:83,Db:85,ga:87,Fa:89,Ib:90,Ga:91,Pa:92,V:93,tc:94,Ja:95,U:96,Rb:97,G:98,I:99,oc:100,Ba:101,La:102,Mb:103,sc:104,ka:105,W:106,za:107,na:108,zb:109,ha:110,wa:111,rc:112,Ob:113,oa:114,S:115,ra:116,jb:117,eb:118,Ha:119,Hb:120,cc:121,Pb:122,jc:123,Xb:124,Za:125,ub:126,Aa:127,dc:128,ob:129,pb:130,ua:131,Xa:132,H:133,Ta:134,Da:135,kb:136,
J:137,uc:138,wb:139,ac:140,Vb:141,nb:142,bb:143,xb:144,R:145,sb:146,Ua:147,ab:148,Jb:149,ma:150,fa:151,Va:152,ta:154,Y:155,mc:156,kc:157,Ra:158,sa:159,M:160,aa:161,la:162,bc:163,Lb:164,qa:165,da:166,Sb:167,ea:168,Ya:169,Wa:170,Ia:171,ya:172,Kb:173,rb:174,Ab:175,Bb:176,vb:177,Cb:178,Zb:179,ic:180,ba:181,ja:182,T:183,D:184,Eb:185,Ma:186,gb:187,ca:188,ia:189,ib:190,N:191,P:192,cb:193,Tb:194,Ea:195,yb:196,xa:197,Ub:198,hb:200,va:201,Na:202,mb:203,qb:204,Fb:205};var r,t;a:{for(var fa=["CLOSURE_FLAGS"],u=d,ha=0;ha<fa.length;ha++)if(u=u[fa[ha]],null==u){t=null;break a}t=u}var ia=t&&t[610401301];r=null!=ia?ia:!1;var v;const ka=d.navigator;v=ka?ka.userAgentData||null:null;function la(a){return r?v?v.brands.some(({brand:b})=>b&&-1!=b.indexOf(a)):!1:!1}function w(a){var b;a:{if(b=d.navigator)if(b=b.userAgent)break a;b=""}return-1!=b.indexOf(a)};function z(){return r?!!v&&0<v.brands.length:!1}function ma(){return z()?la("Chromium"):(w("Chrome")||w("CriOS"))&&!(z()?0:w("Edge"))||w("Silk")};var na=z()?!1:w("Trident")||w("MSIE");!w("Android")||ma();ma();w("Safari")&&(ma()||(z()?0:w("Coast"))||(z()?0:w("Opera"))||(z()?0:w("Edge"))||(z()?la("Microsoft Edge"):w("Edg/"))||z()&&la("Opera"));var oa={},A=null;var pa="undefined"!==typeof Uint8Array,qa=!na&&"function"===typeof btoa;function B(a){return Array.prototype.slice.call(a)};const C="function"===typeof Symbol&&"symbol"===typeof Symbol()?Symbol():void 0;var E=C?(a,b)=>{a[C]|=b}:(a,b)=>{void 0!==a.g?a.g|=b:Object.defineProperties(a,{g:{value:b,configurable:!0,writable:!0,enumerable:!1}})};function ra(a){const b=F(a);1!==(b&1)&&(Object.isFrozen(a)&&(a=B(a)),G(a,b|1))}
var sa=C?(a,b)=>{a[C]&=~b}:(a,b)=>{void 0!==a.g&&(a.g&=~b)},F=C?a=>a[C]|0:a=>a.g|0,H=C?a=>a[C]:a=>a.g,G=C?(a,b)=>{a[C]=b}:(a,b)=>{void 0!==a.g?a.g=b:Object.defineProperties(a,{g:{value:b,configurable:!0,writable:!0,enumerable:!1}})};function ta(a){E(a,1);return a}function I(a){a=a>>11&1023;return 0===a?536870912:a};var ua={};function J(a){return null!==a&&"object"===typeof a&&!Array.isArray(a)&&a.constructor===Object}let va;var K;const wa=[];G(wa,39);K=Object.freeze(wa);function xa(a){if(null==a)return a;if("boolean"===typeof a||"number"===typeof a)return!!a}function ya(a){return a}function L(a){return null==a||"string"===typeof a?a:void 0};let M;function za(a,b){return Ca(b)}
function Ca(a){switch(typeof a){case "number":return isFinite(a)?a:String(a);case "boolean":return a?1:0;case "object":if(a&&!Array.isArray(a)&&pa&&null!=a&&a instanceof Uint8Array){if(qa){for(var b="",c=0,e=a.length-10240;c<e;)b+=String.fromCharCode.apply(null,a.subarray(c,c+=10240));b+=String.fromCharCode.apply(null,c?a.subarray(c):a);a=btoa(b)}else{void 0===b&&(b=0);if(!A){A={};c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split("");e=["+/=","+/","-_=","-_.","-_"];for(var f=
0;5>f;f++){var g=c.concat(e[f].split(""));oa[f]=g;for(var h=0;h<g.length;h++){var k=g[h];void 0===A[k]&&(A[k]=h)}}}b=oa[b];c=Array(Math.floor(a.length/3));e=b[64]||"";for(f=g=0;g<a.length-2;g+=3){var l=a[g],n=a[g+1];k=a[g+2];h=b[l>>2];l=b[(l&3)<<4|n>>4];n=b[(n&15)<<2|k>>6];k=b[k&63];c[f++]=""+h+l+n+k}h=0;k=e;switch(a.length-g){case 2:h=a[g+1],k=b[(h&15)<<2]||e;case 1:a=a[g],c[f]=""+b[a>>2]+b[(a&3)<<4|h>>4]+k+e}a=c.join("")}return a}}return a};function Da(a,b,c,e,f,g){if(null!=a){if(Array.isArray(a))a=f&&0==a.length&&F(a)&1?void 0:g&&F(a)&2?a:Ea(a,b,c,void 0!==e,f,g);else if(J(a)){const h={};for(let k in a)h[k]=Da(a[k],b,c,e,f,g);a=h}else a=b(a,e);return a}}function Ea(a,b,c,e,f,g){const h=e||c?F(a):0;e=e?!!(h&32):void 0;a=B(a);for(let k=0;k<a.length;k++)a[k]=Da(a[k],b,c,e,f,g);c&&c(h,a);return a}function Fa(a){return a.A===ua?a.toJSON():Ca(a)};var N=function(a,b){a=a.l;return Ga(a,H(a),b)},Ga=function(a,b,c){if(-1===c)return null;if(c>=I(b)){if(b&256)return a[a.length-1][c]}else if(b=c+(+!!(b&512)-1),b<a.length)return a[b]};function Ha(a,b,c,e){var f=I(b);if(c>=f){let g=b;if(b&256)f=a[a.length-1];else{if(null==e)return;f=a[f+(+!!(b&512)-1)]={};g|=256}f[c]=e;g!==b&&G(a,g)}else a[c+(+!!(b&512)-1)]=e,b&256&&(a=a[a.length-1],c in a&&delete a[c])}
function O(a,b,c){a=a.l;const e=H(a),f=e&2;var g=e&2,h=Ga(a,e,b);Array.isArray(h)||(h=K);var k=F(h);k&1||ta(h);g?k&2||E(h,34):k&32&&!(k&2)&&sa(h,32);g=h;h=F(g);if(!(h&4)){Object.isFrozen(g)&&(h=0,g=B(g),Ha(a,e,b,g));let l=k=0;for(;k<g.length;k++){const n=c(g[k]);null!=n&&(g[l++]=n)}l<k&&(g.length=l);h|=5;f&&(h|=34);G(g,h);h&2&&Object.freeze(g)}!f&&(h&2||Object.isFrozen(g))&&(g=B(g),E(g,5),Ha(a,e,b,g));return g}function Ia(a){a=a.l;const b=H(a);if(b&2)throw Error();Ha(a,b,2,"en")}
function P(a,b){return null!=a?a:b}var Q=function(a,b){return P(L(N(a,b)),"")};var Ja=function(){var a=R.config;va=!0;try{return JSON.stringify(a.toJSON(),za)}finally{va=!1}},La=class{constructor(a){a:{null==a&&(a=M);M=void 0;if(null==a){var b=96;a=[]}else{if(!Array.isArray(a))throw Error();b=F(a);if(b&64)break a;var c=a;b|=64;var e=c.length;if(e){var f=e-1;e=c[f];if(J(e)){b|=256;const g=+!!(b&512)-1;f-=g;if(1024<=f){f=1023+g;const h=c.length;for(let k=f;k<h;k++){const l=c[k];null!=l&&l!==e&&(e[k-g]=l)}c.length=f+1;c[f]=e;f=1023}b=b&-2095105|(f&1023)<<11}}}G(a,b)}this.l=a}toJSON(){if(va)var a=
Ka(this,this.l,!1);else a=Ea(this.l,Fa,void 0,void 0,!1,!1),a=Ka(this,a,!0);return a}};La.prototype.A=ua;La.prototype.toString=function(){return Ka(this,this.l,!1).toString()};
function Ka(a,b,c){var e=a.constructor.B,f=I(H(c?a.l:b)),g=!1;if(e){if(!c){b=B(b);var h;if(b.length&&J(h=b[b.length-1]))for(g=0;g<e.length;g++)if(e[g]>=f){Object.assign(b[b.length-1]={},h);break}g=!0}f=b;c=!c;h=H(a.l);a=I(h);h=+!!(h&512)-1;var k;for(let x=0;x<e.length;x++){var l=e[x];if(l<a){l+=h;var n=f[l];null==n?f[l]=c?K:ta([]):c&&n!==K&&ra(n)}else{if(!k){var D=void 0;f.length&&J(D=f[f.length-1])?k=D:f.push(k={})}n=k[l];null==k[l]?k[l]=c?K:ta([]):c&&n!==K&&ra(n)}}}e=b.length;if(!e)return b;let Aa,
Ba;if(J(k=b[e-1])){a:{var y=k;D={};f=!1;for(let x in y)c=y[x],Array.isArray(c)&&c!=c&&(f=!0),null!=c?D[x]=c:f=!0;if(f){for(let x in D){y=D;break a}y=null}}y!=k&&(Aa=!0);e--}for(;0<e;e--){k=b[e-1];if(null!=k)break;Ba=!0}if(!Aa&&!Ba)return b;var ja;g?ja=b:ja=Array.prototype.slice.call(b,0,e);b=ja;g&&(b.length=e);y&&b.push(y);return b};var Ma=class extends La{getTenantId(){return P(N(this,1),0)}getLocale(){return Q(this,2)}getInsecureHost(){return Q(this,7)}},Na=function(a){return b=>{if(null==b||""==b)b=new a;else{b=JSON.parse(b);if(!Array.isArray(b))throw Error(void 0);E(b,32);M=b;b=new a(b);M=void 0}return b}}(Ma);Ma.B=[10,12,13,21,22];var S;var Oa=class{constructor(a){this.g=a}toString(){return this.g+""}},Pa={};var Qa=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^\\\\/?#]*)@)?([^\\\\/?#]*?)(?::([0-9]+))?(?=[\\\\/?#]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#([\\s\\S]*))?$"),Ra=function(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var e=a[c].indexOf("="),f=null;if(0<=e){var g=a[c].substring(0,e);f=a[c].substring(e+1)}else g=a[c];b(g,f?decodeURIComponent(f.replace(/\+/g," ")):"")}}};var T=function(a){this.j=this.u=this.i="";this.s=null;this.m=this.o="";this.g=!1;if(a instanceof T){this.g=a.g;Sa(this,a.i);this.u=a.u;this.j=a.j;Ta(this,a.s);this.o=a.o;var b=a.h;var c=new U;c.i=b.i;b.g&&(c.g=new Map(b.g),c.h=b.h);Ua(this,c);this.m=a.m}else a&&(b=String(a).match(Qa))?(this.g=!1,Sa(this,b[1]||"",!0),this.u=V(b[2]||""),this.j=V(b[3]||"",!0),Ta(this,b[4]),this.o=V(b[5]||"",!0),Ua(this,b[6]||"",!0),this.m=V(b[7]||"")):(this.g=!1,this.h=new U(null,this.g))};
T.prototype.toString=function(){var a=[],b=this.i;b&&a.push(W(b,Va,!0),":");var c=this.j;if(c||"file"==b)a.push("//"),(b=this.u)&&a.push(W(b,Va,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.s,null!=c&&a.push(":",String(c));if(c=this.o)this.j&&"/"!=c.charAt(0)&&a.push("/"),a.push(W(c,"/"==c.charAt(0)?Wa:Xa,!0));(c=this.h.toString())&&a.push("?",c);(c=this.m)&&a.push("#",W(c,Ya));return a.join("")};
var Sa=function(a,b,c){a.i=c?V(b,!0):b;a.i&&(a.i=a.i.replace(/:$/,""))},Ta=function(a,b){if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.s=b}else a.s=null},Ua=function(a,b,c){b instanceof U?(a.h=b,Za(a.h,a.g)):(c||(b=W(b,$a)),a.h=new U(b,a.g))},ab=function(a){return a instanceof T?new T(a):new T(a)},V=function(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""},W=function(a,b,c){return"string"===typeof a?(a=encodeURI(a).replace(b,bb),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,
"%$1")),a):null},bb=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)},Va=/[#\/\?@]/g,Xa=/[#\?:]/g,Wa=/[#\?]/g,$a=/[#\?@]/g,Ya=/#/g,U=function(a,b){this.h=this.g=null;this.i=a||null;this.j=!!b},X=function(a){a.g||(a.g=new Map,a.h=0,a.i&&Ra(a.i,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))};U.prototype.add=function(a,b){X(this);this.i=null;a=Y(this,a);var c=this.g.get(a);c||this.g.set(a,c=[]);c.push(b);this.h+=1;return this};
var cb=function(a,b){X(a);b=Y(a,b);a.g.has(b)&&(a.i=null,a.h-=a.g.get(b).length,a.g.delete(b))},db=function(a,b){X(a);b=Y(a,b);return a.g.has(b)};U.prototype.forEach=function(a,b){X(this);this.g.forEach(function(c,e){c.forEach(function(f){a.call(b,f,e,this)},this)},this)};var eb=function(a,b){X(a);let c=[];if("string"===typeof b)db(a,b)&&(c=c.concat(a.g.get(Y(a,b))));else for(a=Array.from(a.g.values()),b=0;b<a.length;b++)c=c.concat(a[b]);return c};
U.prototype.set=function(a,b){X(this);this.i=null;a=Y(this,a);db(this,a)&&(this.h-=this.g.get(a).length);this.g.set(a,[b]);this.h+=1;return this};U.prototype.get=function(a,b){if(!a)return b;a=eb(this,a);return 0<a.length?String(a[0]):b};
U.prototype.toString=function(){if(this.i)return this.i;if(!this.g)return"";const a=[],b=Array.from(this.g.keys());for(var c=0;c<b.length;c++){var e=b[c];const g=encodeURIComponent(String(e)),h=eb(this,e);for(e=0;e<h.length;e++){var f=g;""!==h[e]&&(f+="="+encodeURIComponent(String(h[e])));a.push(f)}}return this.i=a.join("&")};
var Y=function(a,b){b=String(b);a.j&&(b=b.toLowerCase());return b},Za=function(a,b){b&&!a.j&&(X(a),a.i=null,a.g.forEach(function(c,e){var f=e.toLowerCase();if(e!=f&&(cb(this,e),cb(this,f),0<c.length)){this.i=null;e=this.g;var g=e.set;f=Y(this,f);var h=c.length;if(0<h){const k=Array(h);for(let l=0;l<h;l++)k[l]=c[l];h=k}else h=[];g.call(e,f,h);this.h+=c.length}},a));a.j=b};/*

 SPDX-License-Identifier: Apache-2.0
*/
const fb={};function gb(a,b){var c=fb[a];if(void 0!==c&&(!c.v||Date.now()<=c.v+3E5))return c.p;c=new Promise((f,g)=>{b.onload=()=>f(b);b.onerror=h=>{b.parentNode&&b.parentNode.removeChild(b);g(h)};document.head.appendChild(b)});const e={v:0,p:c};c.catch(()=>e.v=+new Date);fb[a]=e;return c}
var hb=function(a){a=ab(a);const b=document.createElement("script");var c=a.toString();c=null===c?"null":void 0===c?"undefined":c;if(void 0===S){var e=null;var f=d.trustedTypes;if(f&&f.createPolicy){try{e=f.createPolicy("goog#html",{createHTML:p,createScript:p,createScriptURL:p})}catch(k){d.console&&d.console.error(k.message)}S=e}else S=e}c=(e=S)?e.createScriptURL(c):c;c=new Oa(c,Pa);b.src=c instanceof Oa&&c.constructor===Oa?c.g:"type_error:TrustedResourceUrl";var g;let h;(g=(c=null==(h=(g=(b.ownerDocument&&
b.ownerDocument.defaultView||window).document).querySelector)?void 0:h.call(g,"script[nonce]"))?c.nonce||c.getAttribute("nonce")||"":"")&&b.setAttribute("nonce",g);return gb(a.toString(),b)};class ib{constructor(){this.promise=new Promise(a=>{this.g=a})}};var Z=function(a="Devsite has failed to load."){throw Error(a);},kb=async function(){var a=R;const b=new ib;m("__devsiteAppReadyResolver",b.g);m("__devsiteAppReadyPromise",b.promise);m("DevsiteApp.whenReady",()=>b.promise);if(O(a.config,12,L).length)try{await Promise.all(O(a.config,12,L).map(f=>{f=ab(f);const g=document.createElement("link");g.setAttribute("rel","stylesheet");g.setAttribute("type","text/css");g.setAttribute("href",f.toString());return gb(f.toString(),g)}))}catch(f){Z(`Failed to load Devsite App dependencies: ${f.message}`)}const c=
d.DevsiteAppTenantCustomized?Q(a.config,6):Q(a.config,5);try{await hb(`${c}${jb(a)}`)}catch(f){if("en"!==a.config.getLocale()){Ia(a.config);try{await hb(`${c}${Q(a.config,4)}`)}catch(g){Z(`Failed to load Devsite App binary: ${g.message}`)}}else Z(`Failed to load Devsite App binary: ${f.message}`)}const e=document;if("complete"!==e.readyState&&"interactive"!==e.readyState){const f=new ib;e.addEventListener("readystatechange",()=>{"interactive"!==e.readyState&&"complete"!==e.readyState||f.g()});await f.promise}},
jb=function(a){const b=a.config.getLocale();a=Q(a.config,4);return b&&"en"!==b?a.replace(/\.js$/,`__${b.toLowerCase().replace("-","_")}.js`):a};
const R=new class{constructor(){this.g=null;this.config=new Ma;this.h=[];this.i=a=>{this.h.push(a)};this.m=()=>{this.j()};if(d.__globalAppLoader)return d.__globalAppLoader;try{this.config=Na(`${GoogleDevelopersObject}`.replaceAll("\n",""))}catch(a){Z("GoogleDevelopersObject missing or invalid")}GoogleDevelopersObject=null;m("__globalAppLoader",this);m("DevsiteApp.hasFlagAccess",a=>this.hasFlagAccess(a));m("DevsiteApp.hasMendelFlagAccess",(a,b)=>this.hasMendelFlagAccess(a,b))}j(){var a=document.querySelector("devsite-content");
a&&(window.removeEventListener("message",this.i),a.removeEventListener("devsite-content-updated",this.m));a=window;for(const b of this.h)a.dispatchEvent(b);this.h=[]}getEnv(){if(P(xa(N(this.config,11)),!1))return"PROD";const a=document.location.hostname;return a.endsWith("test.devsite.corp.google.com")||a.endsWith("test.devsite-v2-staging.googleplex.com")?"TEST":a.endsWith(".devsite.corp.google.com")||a.endsWith("devsite-v2-staging.googleplex.com")?"STAGE":"DEV"}hasFlagAccess(a){a:{var b=this.getEnv(),
c=O(this.config,13,ya),e=new URL(document.location.toString());e=new T(e.href);const f=Object.keys(ea);if("PROD"!==b)for(const g of f)if(ea[g]===a&&(b=e.h.get(g),void 0!==b)){a="true"===b;break a}a=Array.from(c).includes(a)}return a}hasMendelFlagAccess(a,b){a:{var c=this.getEnv();var e=O(this.config,22,L);var f=new URL(document.location.toString());f=new T(f.href);a=a+"__"+b;if("PROD"!==c&&(c=f.h.get(a),void 0!==c)){e="true"===c;break a}e=Array.from(e).includes(a)}return e}},lb=document.querySelector("devsite-content");
lb&&(window.addEventListener("message",R.i),lb.addEventListener("devsite-content-updated",R.j.bind(R)));(async function(){const a=window;if("WeakMap"in a&&"performance"in a&&"now"in a.performance)return R.g||(R.g=kb()),R.g})().then(()=>{P(xa(N(R.config,9)),!1)?(d.DevsiteAppFrameboxInit||Z("Failed to load Devsite App binary"),DevsiteAppFrameboxInit(Ja(),d.DevsiteAppAuthorizedElements)):(d.DevsiteAppInit||Z("Failed to load Devsite App binary"),DevsiteAppInit(Ja(),d.DevsiteAppAuthorizedElements))});}).call(this);
