(function(_ds){var window=this;var y0=function(a){return!a.classList.contains("material-icons")},G0=async function(a,b){await DevsiteApp.whenReady();const c=_ds.E();var d=DevsiteApp.getInsecureHost();b=b.Ia;if(b.origin===c.origin||!d||b.origin===d){try{var e=(0,_ds.dn)(b.data)}catch(g){return}d=_ds.kg(e,1);if(4===d)z0(a,b);else{var f=e.getName();if(f&&(f=a.querySelector(`devsite-iframe iframe[name="${f}"]`)))switch(d){case 5:A0(e,f);break;case 8:B0(b,e,c);break;case 1:C0(b,e,c);break;case 6:case 7:D0(d,c,e);break;case 9:E0(a,e);
break;case 10:F0(e,c)}}}},H0=function(a){Array.from(a.querySelectorAll("table.lazy-load")).forEach(b=>{b.classList.remove("hidden")})},M0=function(a){I0(a);a.v=a.querySelector(".devsite-article-body");a.v&&(J0(a),a.ea=[]);a.g&&a.g.disconnect();a.h.clear();K0(a);if(!document.body.hasAttribute("appearance")){var b=[...a.querySelectorAll("picture > source.devsite-dark-theme")];for(var c of b){b=c.closest("picture");const d=b.querySelector("img");b.querySelectorAll("source:not(.devsite-dark-theme)").length?
c.remove():b&&d&&b.replaceWith(d)}}c=Array.from(a.querySelectorAll(".devsite-nav-title, .devsite-page-title, td > code, th > code"));"docs"===document.body.getAttribute("layout")&&a.v&&(b=Array.from(a.v.querySelectorAll("h1, h2, h3, h4, h5, h6")),c.push(...b));a.h.clear();a.h=new Set(c);if(_ds.E().hash){c=new _ds.rK;for(const d of a.h)_ds.qK(c,d,y0)}else L0(a,a.h);a.dispatchEvent(new CustomEvent("devsite-content-updated",{bubbles:!0}))},K0=function(a){Array.from(a.getElementsByTagName("table")).forEach(b=>
{if(!b.parentNode.classList.contains("devsite-table-wrapper")){var c=document.createElement("div");c.classList.add("devsite-table-wrapper");b.classList.contains("full-width")&&(c.classList.add("devsite-full-width-table"),b.classList.remove("full-width"));_ds.sj(c,b);c.appendChild(b)}})},I0=function(a){Array.from(a.querySelectorAll("table.lazy-load")).forEach(b=>{b.classList.add("hidden")})},z0=async function(a,b){const c=N0(a,b.source);if(c){const e="goog_"+_ds.Yi++;c.setAttribute("name",e);var d=
_ds.bn(3);d=_ds.dg(d,2,e);(b=b.source)&&b.postMessage(_ds.ng(d),"*");(b=document.body.getAttribute("appearance"))&&O0(c,b);a.ea.push(c)}},A0=async function(a,b){const c=_ds.kj(document).y,d=_ds.ig(a,4);a=_ds.ig(a,3);b=_ds.Aj(b);d&&b.setAttribute("width",`${d}px`);a&&b.setAttribute("height",`${a}px`);window.requestAnimationFrame(()=>{window.scrollTo(_ds.kj(document).x,c)})},B0=async function(a,b,c){b=_ds.cn(_ds.bn(8),_ds.z(b,8));c=_ds.dg(b,6,c.toString());(a=a.source)&&a.postMessage(_ds.ng(c),"*")},
C0=async function(a,b,c){b=_ds.cn(_ds.bn(2),_ds.z(b,8));c=_ds.dg(b,7,`${c.search}${c.hash}`);(a=a.source)&&a.postMessage(_ds.ng(c),"*")},D0=async function(a,b,c){const d=c.getTitle();b=new URL(c.getUrl(),b.origin);b=`${window.location.origin}${window.location.pathname}${b.search}${b.hash}`;6===a?window.history.pushState({},d,b):window.history.replaceState({},d,b)},E0=async function(a,b){const c=_ds.z(b,9);let d;try{d=JSON.parse(_ds.z(b,10))}catch(e){console.warn("Event data from Framebox is not valid JSON.",
a);return}"analyticsEvent"===c?a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:d,bubbles:!0})):"cloudtrackEvent"===c?a.dispatchEvent(new CustomEvent("devsite-analytics-observation-cloudtrack",{detail:{eventData:d},bubbles:!0})):"devsite-apix"===c&&a.dispatchEvent(new CustomEvent("devsite-apix-observation",{detail:d,bubbles:!0}))},F0=async function(a,b){if(a=a.getUrl()){const c=new URL(a,b.origin);a.startsWith("#")||b.origin===c.origin&&b.pathname===c.pathname&&b.search===c.search?
DevsiteApp.scrollToAnchor(c.hash,!0):DevsiteApp.fetchPage(c.href)}},N0=function(a,b){let c;Array.from(a.querySelectorAll("devsite-iframe iframe")).forEach(d=>{_ds.Bj(d)===b&&(c=d)});return c},O0=function(a,b){var c=_ds.bn(12);b=_ds.dg(c,12,b);a&&a.contentWindow&&(a=a.contentWindow)&&a.postMessage(_ds.ng(b),"*")},J0=function(a){"full"===document.body.getAttribute("layout")&&(a=a.v.querySelectorAll('h1[tabindex="0"],h2[tabindex="0"],h3[tabindex="0"],h4[tabindex="0"],h5[tabindex="0"],h6[tabindex="0"]'))&&
Array.from(a).forEach(b=>{b.removeAttribute("tabindex")})},L0=function(a,b){a.g&&b.forEach(c=>{a.g.observe(c)})},P0=class extends _ds.D{constructor(){super();this.o=new _ds.F;this.ma=new _ds.F;this.h=new Set;this.ea=[];this.g=null;"IntersectionObserver"in window&&(this.g=new IntersectionObserver(a=>{for(const b of a)b.isIntersecting&&(a=b.target,_ds.qK(new _ds.rK,a,y0),this.h.delete(a),this.g.unobserve(a))},{rootMargin:"100%"}))}connectedCallback(){this.o.listen(window,"message",a=>G0(this,a));this.o.listen(document.body,
"devsite-appearance-updated",a=>{if((a=a.Ia.detail.preference)&&this.ea.length)for(const b of this.ea)O0(b,a)});this.o.listen(document.body,"devsite-page-loaded",()=>void H0(this));M0(this)}disconnectedCallback(){this.g&&this.g.disconnect();this.h.clear();_ds.H(this.o);_ds.H(this.ma)}Wb(a){a&&([".devsite-article",".devsite-content-data","devsite-content-footer","devsite-notification"].forEach(b=>{_ds.ri(this,this.querySelector(b),a.querySelector(b))}),M0(this))}};P0.prototype.updateContent=P0.prototype.Wb;
P0.prototype.disconnectedCallback=P0.prototype.disconnectedCallback;P0.prototype.connectedCallback=P0.prototype.connectedCallback;try{window.customElements.define("devsite-content",P0)}catch(a){console.warn("devsite.app.customElement.DevsiteContent",a)};})(_ds_www);
